services:
  - type: cron
    name: leads-scraper
    env: python
    schedule: "0 2 * * *"  # Runs daily at 2 AM
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium
    startCommand: python multi_session_scraper.py
    plan: starter